// <auto-generated />
using System;
using AzilEdu.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzilEdu.Api.Migrations
{
    [DbContext(typeof(AzilEduDbContext))]
    [Migration("20260330213055_AddAnimalStatusRelation")]
    partial class AddAnimalStatusRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AzilEdu.Shared.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalStatusId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 3,
                            AnimalStatusId = 1,
                            ArrivalDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Mješanac",
                            Description = "Mirna i druželjubiva kujica.",
                            Gender = "Ženka",
                            ImageUrl = "/images/animals/luna.webp",
                            Name = "Luna",
                            Species = "Pas"
                        },
                        new
                        {
                            Id = 2,
                            Age = 5,
                            AnimalStatusId = 2,
                            ArrivalDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Labrador",
                            Description = "Aktivan pas koji voli šetnje.",
                            Gender = "Mužjak",
                            ImageUrl = "/images/animals/rex.webp",
                            Name = "Rex",
                            Species = "Pas"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.AnimalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AnimalStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dostupna za udomljenje"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rezervirana"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Udomljena"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Na liječenju"
                        });
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.Animal", b =>
                {
                    b.HasOne("AzilEdu.Shared.Models.AnimalStatus", "AnimalStatus")
                        .WithMany("Animals")
                        .HasForeignKey("AnimalStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnimalStatus");
                });

            modelBuilder.Entity("AzilEdu.Shared.Models.AnimalStatus", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
